In [1]:
x = 4 + 5

In [2]:
x

9

In [3]:
a = 5/4
a

1.25

In [4]:
b = 5%4
b

1

In [5]:
c = 7//8

In [6]:
c

0

In [7]:
c = 8//7
c

1

In [8]:
for i in range(5):
    print(i)

0
1
2
3
4


In [9]:
for i in range(1,5):
    print(i)

1
2
3
4


In [10]:
for i in range(5,0,-2):
    print(i)

5
3
1


In [11]:
def http_error(status):
    match status:
        case 200:
            return 'OK'
        case 400:
            return 'Bad request'
        case 401 | 403 | 404:
            return 'Not allowed'
        case _:
            return 'Something is wrong'


print(http_error(200))
print(http_error(404))
print(http_error(12345))
print(http_error('abc'))

OK
Not allowed
Something is wrong
Something is wrong


In [12]:
set_a = {1,2,3,4,5,6}
set_b = {3,4,5,6,7,8}
print(set_a|set_b)
print(set_a & set_b)
print(set_a - set_b)
print(set_a ^ set_b)

{1, 2, 3, 4, 5, 6, 7, 8}
{3, 4, 5, 6}
{1, 2}
{1, 2, 7, 8}


In [16]:
import copy
li1 = [1, 2, [3, 5], 4]
print("li1 ID: ", id(li1), "Value: ", li1)
li2 = copy.copy(li1)
print("li2 ID: ", id(li2), "Value: ", li2)
li4 = copy.copy(li1)
print("li4 ID: ", id(li4), "Value: ", li4)
li3 = copy.deepcopy(li1)
print("li3 ID: ", id(li3), "Value: ", li3)

li1 ID:  138245966898432 Value:  [1, 2, [3, 5], 4]
li2 ID:  138245966903680 Value:  [1, 2, [3, 5], 4]
li4 ID:  138245966906112 Value:  [1, 2, [3, 5], 4]
li3 ID:  138245966846656 Value:  [1, 2, [3, 5], 4]


In [20]:
lst = [lambda i=i:i*2 for i in range(5)]
for i in lst:
    print(i)
    print(i())

<function <listcomp>.<lambda> at 0x7dbbe5b730a0>
0
<function <listcomp>.<lambda> at 0x7dbbe5b73b50>
2
<function <listcomp>.<lambda> at 0x7dbbe510c1f0>
4
<function <listcomp>.<lambda> at 0x7dbbe510c3a0>
6
<function <listcomp>.<lambda> at 0x7dbbe510c700>
8


In [25]:
lst = [lambda i:i*2 for i in range(5)]
for i in lst:
    print(i)
    print(i(4))
    

<function <listcomp>.<lambda> at 0x7dbbe51f70a0>
8
<function <listcomp>.<lambda> at 0x7dbbe51f5d80>
8
<function <listcomp>.<lambda> at 0x7dbbe51f72e0>
8
<function <listcomp>.<lambda> at 0x7dbbe51f5e10>
8
<function <listcomp>.<lambda> at 0x7dbbe51f55a0>
8


In [26]:
import numpy as np
x = [[0,1,2],[3,4,5],[6,7,8]]
arr = np.array(x)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

2
(3, 3)
9
int64
8


In [29]:
arr1 = np.arange(0,20)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [30]:
arr2 = np.linspace(0,20,5)
print(arr2)

[ 0.  5. 10. 15. 20.]
